### ISSUE TITLE
Organization logo

### ISSUE THREAD

**Issue by ararslan** [JuliaCollections/Roadmap#2]
It would be nice to have a logo for the organization. Call for proposals!

**Comment by jrevels** [comment]
![julia-collections-logo](https://cloud.githubusercontent.com/assets/3277443/22567781/4c02f7ba-e95f-11e6-9dd2-4805897a0e78.png)

**Comment by ararslan** [comment]
Not bad! Though I'd recommend removing the blue dot to avoid confusion with Julia Computing, the only organization with a logo that includes a fourth dot (AFAIK).

**Comment by jrevels** [comment]
![julia-collections-logo-2](https://cloud.githubusercontent.com/assets/3277443/22568841/455a2c54-e963-11e6-8485-5d00c6004fee.png)

**Comment by yuyichao** [comment]
I'm really not a graphic designer so I don't have a better one but I want to say that 3 circles really look more like a traffic light than something about collections........

**Comment by ararslan** [comment]
Hm. What if the circles were arranged in the iconic triangle?

**Comment by jrevels** [comment]
> look more like a traffic light

Ahhh, cannot unsee! I tried adding commas, but that didn't help and was kind of ugly.

> What if the circles were arranged in the iconic triangle?

I'm too lazy to do that, but I'll send SVGs to anybody who wants to play around with them. These only took like 5 seconds to make, so I'm not too attached 😛

**Comment by yuyichao** [comment]
> Ahhh, cannot unsee!

Yeah, I know I was going to permanently ruin it for someone.... ;-p

**Comment by iamed2** [comment]
Could put the circles in a triangle like this:

```
   O
  / \
 O   O
```
like a tree?

**Comment by cormullion** [comment]
Here's a few ideas I had for this org's logo.

1: "recursive"

![collectionslogo](https://cloud.githubusercontent.com/assets/52289/22862313/29a85512-f124-11e6-88ee-1b28726a2875.png)

2: "iterative"

![collectionslogo2](https://cloud.githubusercontent.com/assets/52289/22862314/29ada1f2-f124-11e6-9187-3e2c3f747043.png)

3: "arrayed"

![collectionslogo3](https://cloud.githubusercontent.com/assets/52289/22862315/29af633e-f124-11e6-9cc8-3df754ad3593.png)

I could later post the Julia code to make them, if you promise not to laugh at my strange coding practices... :)

**Comment by ararslan** [comment]
I really like those, @cormullion, nice work! Though I will say that the first reminds me a fair bit of The Legend of Zelda and the JuliaParallel org logo...

**Comment by cormullion** [comment]
@ararslan I thought going a few more levels deeper than JuliaParallel's would be sufficient. :) 

The Zelda connection is intriguing...

![img](https://s-media-cache-ak0.pinimg.com/736x/c2/5e/3c/c25e3c97ed93536eac98c69840a37fdc.jpg)

**Comment by cormullion** [comment]
I did a few more today as I had a bit of spare time and v0.6 work is temporarily stalled...

![tiled-images](https://cloud.githubusercontent.com/assets/52289/24001427/01d53fe6-0a56-11e7-846d-8419151f6881.png)

**Comment by ararslan** [comment]
I absolutely love all three of those, though none of them strike me as really symbolizing collections. Of those I think the third is my favorite.

**Comment by cormullion** [comment]
:) I originally came here because of the iterators, so perhaps I'm torn between repetitive patterns and object groupings... But they're all collections of shapes... :)

Now that you mention it, I see that you sometimes refer to JuliaContainers rather than collections — which is more oriented towards collections than iterator/collecting patterns.

Anyway, more choice is always good.

**Comment by ararslan** [comment]
Come for the iterators, stay for the logos

**Comment by iamed2** [comment]
I like the ones in https://github.com/JuliaCollections/Roadmap/issues/2#issuecomment-279217657 the best. I think #3 "arrayed" is my favourite.

**Comment by ararslan** [comment]
I agree with Eric, I think "arrayed" is a good choice.

**Comment by cormullion** [comment]
Cool. Not sure how a PR would work, so [here's a gist of the source](https://gist.github.com/cormullion/b9eeac0a03ea8bd8a818f81d19d24852).

**Comment by iamed2** [comment]
That version doesn't seem to have the variation in brightness for the `[]` elements

**Comment by cormullion** [comment]
Oh, yes. I thought it might not show very well when seen at (normal) small size. Perhaps I'll put it back.

**Comment by iamed2** [comment]
I think it's a nice subtle touch that doesn't hurt if you can't see it :)

**Comment by cormullion** [comment]
I put the randomness back. :)

**Comment by ararslan** [comment]
I've set "arrayed" as the org logo. If anyone opposes this, we can always change it. 🙂 Thanks so much for your work here, @cormullion!
